// Automatically generated massive dummy dataset spanning 2019-2030

export const DUMMY_PROPERTIES = [
  {
    "id": 1001,
    "title": "Vista Tower at Arjan",
    "developer": "Azizi Developments",
    "location": "Arjan",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 2,400,000",
    "rawPrice": 2400000,
    "completionDate": "Q4 2028",
    "paymentPlan": "70/30 Payment Plan",
    "bedrooms": "1",
    "bathrooms": "1",
    "area": "Starting from 600 sqft",
    "roi": "7%",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by Azizi Developments located in the heart of Arjan. Built in 2028.",
    "downPayment": "13%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1002,
    "title": "Vista Estates at Town",
    "developer": "Emaar Properties",
    "location": "Town Square",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 11,200,000",
    "rawPrice": 11200000,
    "completionDate": "Q3 2023",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1-2",
    "bathrooms": "1-2",
    "area": "Starting from 600 sqft",
    "roi": "5%",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Emaar Properties located in the heart of Town Square. Built in 2023.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1003,
    "title": "Vista Park at Business",
    "developer": "Nakheel",
    "location": "Business Bay",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 14,300,000",
    "rawPrice": 14300000,
    "completionDate": "Q1 2022",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1-3",
    "bathrooms": "1-3",
    "area": "Starting from 600 sqft",
    "roi": "5%",
    "image": "https://images.unsplash.com/photo-1449844908441-8829872d2607?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Nakheel located in the heart of Business Bay. Built in 2022.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1004,
    "title": "Signature Park at Meydan",
    "developer": "Binghatti Developers",
    "location": "Meydan",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 3,400,000",
    "rawPrice": 3400000,
    "completionDate": "Q3 2028",
    "paymentPlan": "70/40 Payment Plan",
    "bedrooms": "4",
    "bathrooms": "4",
    "area": "Starting from 2,400 sqft",
    "roi": "10%",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by Binghatti Developers located in the heart of Meydan. Built in 2028.",
    "downPayment": "22%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1005,
    "title": "Heights Boulevard at Town",
    "developer": "Azizi Developments",
    "location": "Town Square",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 8,700,000",
    "rawPrice": 8700000,
    "completionDate": "Q3 2019",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "2-3",
    "bathrooms": "2-3",
    "area": "Starting from 1,200 sqft",
    "roi": "7%",
    "image": "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Azizi Developments located in the heart of Town Square. Built in 2019.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1006,
    "title": "Exclusive Boulevard at Dubai",
    "developer": "Azizi Developments",
    "location": "Dubai South",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 4,200,000",
    "rawPrice": 4200000,
    "completionDate": "Q4 2022",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "3",
    "bathrooms": "3",
    "area": "Starting from 1,800 sqft",
    "roi": "6%",
    "image": "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by Azizi Developments located in the heart of Dubai South. Built in 2022.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1007,
    "title": "Vista Park at Arjan",
    "developer": "Sobha Realty",
    "location": "Arjan",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 17,900,000",
    "rawPrice": 17900000,
    "completionDate": "Q2 2027",
    "paymentPlan": "70/60 Payment Plan",
    "bedrooms": "2",
    "bathrooms": "2",
    "area": "Starting from 1,200 sqft",
    "roi": "7%",
    "image": "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Sobha Realty located in the heart of Arjan. Built in 2027.",
    "downPayment": "20%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1008,
    "title": "Grand Boulevard at Al",
    "developer": "Omniyat",
    "location": "Al Furjan",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 6,400,000",
    "rawPrice": 6400000,
    "completionDate": "Q1 2025",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "2",
    "bathrooms": "2",
    "area": "Starting from 1,200 sqft",
    "roi": "12%",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Omniyat located in the heart of Al Furjan. Built in 2025.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1009,
    "title": "Luxury Villas at Sobha",
    "developer": "Deyaar",
    "location": "Sobha Hartland",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 14,400,000",
    "rawPrice": 14400000,
    "completionDate": "Q2 2030",
    "paymentPlan": "50/40 Payment Plan",
    "bedrooms": "3-4",
    "bathrooms": "3-4",
    "area": "Starting from 1,800 sqft",
    "roi": "6%",
    "image": "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Deyaar located in the heart of Sobha Hartland. Built in 2030.",
    "downPayment": "17%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1010,
    "title": "Signature Views at Jumeirah",
    "developer": "Dubai Properties",
    "location": "Jumeirah Village Circle (JVC)",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 7,100,000",
    "rawPrice": 7100000,
    "completionDate": "Q2 2021",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "3",
    "bathrooms": "3",
    "area": "Starting from 1,800 sqft",
    "roi": "12%",
    "image": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Dubai Properties located in the heart of Jumeirah Village Circle (JVC). Built in 2021.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1011,
    "title": "Royal Gardens at Dubai",
    "developer": "Sobha Realty",
    "location": "Dubai Sports City",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 7,000,000",
    "rawPrice": 7000000,
    "completionDate": "Q1 2019",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1-3",
    "bathrooms": "1-3",
    "area": "Starting from 600 sqft",
    "roi": "9%",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Sobha Realty located in the heart of Dubai Sports City. Built in 2019.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1012,
    "title": "Oasis Tower at Dubai",
    "developer": "Dubai Properties",
    "location": "Dubai South",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 1,400,000",
    "rawPrice": 1400000,
    "completionDate": "Q2 2024",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4",
    "bathrooms": "4",
    "area": "Starting from 2,400 sqft",
    "roi": "8%",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by Dubai Properties located in the heart of Dubai South. Built in 2024.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1013,
    "title": "Premium Gardens at Dubai",
    "developer": "Danube Properties",
    "location": "Dubai Creek Harbour",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 12,500,000",
    "rawPrice": 12500000,
    "completionDate": "Q2 2028",
    "paymentPlan": "50/30 Payment Plan",
    "bedrooms": "4-6",
    "bathrooms": "4-6",
    "area": "Starting from 2,400 sqft",
    "roi": "5%",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Danube Properties located in the heart of Dubai Creek Harbour. Built in 2028.",
    "downPayment": "16%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1014,
    "title": "Oasis Gardens at Business",
    "developer": "Deyaar",
    "location": "Business Bay",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 16,700,000",
    "rawPrice": 16700000,
    "completionDate": "Q3 2019",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "2-3",
    "bathrooms": "2-3",
    "area": "Starting from 1,200 sqft",
    "roi": "11%",
    "image": "https://images.unsplash.com/photo-1449844908441-8829872d2607?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Deyaar located in the heart of Business Bay. Built in 2019.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1015,
    "title": "Signature Views at Dubai",
    "developer": "Sobha Realty",
    "location": "Dubai Sports City",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 8,200,000",
    "rawPrice": 8200000,
    "completionDate": "Q3 2021",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4",
    "bathrooms": "4",
    "area": "Starting from 2,400 sqft",
    "roi": "6%",
    "image": "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Sobha Realty located in the heart of Dubai Sports City. Built in 2021.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1016,
    "title": "Signature Gardens at Business",
    "developer": "Sobha Realty",
    "location": "Business Bay",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 14,300,000",
    "rawPrice": 14300000,
    "completionDate": "Q2 2025",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1-2",
    "bathrooms": "1-2",
    "area": "Starting from 600 sqft",
    "roi": "10%",
    "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Sobha Realty located in the heart of Business Bay. Built in 2025.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1017,
    "title": "Exclusive Gardens at Meydan",
    "developer": "Binghatti Developers",
    "location": "Meydan",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 700,000",
    "rawPrice": 700000,
    "completionDate": "Q4 2022",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "3-4",
    "bathrooms": "3-4",
    "area": "Starting from 1,800 sqft",
    "roi": "9%",
    "image": "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by Binghatti Developers located in the heart of Meydan. Built in 2022.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1018,
    "title": "Royal Residences at Palm",
    "developer": "DAMAC Properties",
    "location": "Palm Jumeirah",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 3,000,000",
    "rawPrice": 3000000,
    "completionDate": "Q2 2024",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "3",
    "bathrooms": "3",
    "area": "Starting from 1,800 sqft",
    "roi": "8%",
    "image": "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by DAMAC Properties located in the heart of Palm Jumeirah. Built in 2024.",
    "downPayment": "100%",
    "isFeatured": true,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1019,
    "title": "Oasis Gardens at Downtown",
    "developer": "Nakheel",
    "location": "Downtown Dubai",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 6,900,000",
    "rawPrice": 6900000,
    "completionDate": "Q1 2022",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1",
    "bathrooms": "1",
    "area": "Starting from 600 sqft",
    "roi": "6%",
    "image": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Nakheel located in the heart of Downtown Dubai. Built in 2022.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1020,
    "title": "Premium Residences at Business",
    "developer": "Azizi Developments",
    "location": "Business Bay",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 10,700,000",
    "rawPrice": 10700000,
    "completionDate": "Q3 2023",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "2",
    "bathrooms": "2",
    "area": "Starting from 1,200 sqft",
    "roi": "7%",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Azizi Developments located in the heart of Business Bay. Built in 2023.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1021,
    "title": "Elite Heights at Dubai",
    "developer": "Nshama",
    "location": "Dubai Creek Harbour",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 10,000,000",
    "rawPrice": 10000000,
    "completionDate": "Q1 2019",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4",
    "bathrooms": "4",
    "area": "Starting from 2,400 sqft",
    "roi": "10%",
    "image": "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Nshama located in the heart of Dubai Creek Harbour. Built in 2019.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1022,
    "title": "Oasis Views at Al",
    "developer": "Omniyat",
    "location": "Al Furjan",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 1,400,000",
    "rawPrice": 1400000,
    "completionDate": "Q2 2028",
    "paymentPlan": "40/50 Payment Plan",
    "bedrooms": "3-4",
    "bathrooms": "3-4",
    "area": "Starting from 1,800 sqft",
    "roi": "10%",
    "image": "https://images.unsplash.com/photo-1600566753086-00f18efc2294?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by Omniyat located in the heart of Al Furjan. Built in 2028.",
    "downPayment": "11%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1023,
    "title": "Oasis Villas at Jumeirah",
    "developer": "Meraas",
    "location": "Jumeirah Village Circle (JVC)",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 13,000,000",
    "rawPrice": 13000000,
    "completionDate": "Q2 2023",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "2-4",
    "bathrooms": "2-4",
    "area": "Starting from 1,200 sqft",
    "roi": "8%",
    "image": "https://images.unsplash.com/photo-1600566753086-00f18efc2294?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Meraas located in the heart of Jumeirah Village Circle (JVC). Built in 2023.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1024,
    "title": "Signature Estates at Dubai",
    "developer": "MAG Property Development",
    "location": "Dubai Hills Estate",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 12,500,000",
    "rawPrice": 12500000,
    "completionDate": "Q3 2024",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "3-5",
    "bathrooms": "3-5",
    "area": "Starting from 1,800 sqft",
    "roi": "11%",
    "image": "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by MAG Property Development located in the heart of Dubai Hills Estate. Built in 2024.",
    "downPayment": "100%",
    "isFeatured": true,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1025,
    "title": "Vista Heights at Jumeirah",
    "developer": "Meraas",
    "location": "Jumeirah Lake Towers (JLT)",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 5,200,000",
    "rawPrice": 5200000,
    "completionDate": "Q1 2027",
    "paymentPlan": "80/20 Payment Plan",
    "bedrooms": "2-4",
    "bathrooms": "2-4",
    "area": "Starting from 1,200 sqft",
    "roi": "8%",
    "image": "https://images.unsplash.com/photo-1600566753086-00f18efc2294?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Meraas located in the heart of Jumeirah Lake Towers (JLT). Built in 2027.",
    "downPayment": "21%",
    "isFeatured": true,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1026,
    "title": "Premium Gardens at Dubai",
    "developer": "Azizi Developments",
    "location": "Dubai Sports City",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 19,200,000",
    "rawPrice": 19200000,
    "completionDate": "Q4 2026",
    "paymentPlan": "80/50 Payment Plan",
    "bedrooms": "2",
    "bathrooms": "2",
    "area": "Starting from 1,200 sqft",
    "roi": "5%",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Azizi Developments located in the heart of Dubai Sports City. Built in 2026.",
    "downPayment": "16%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1027,
    "title": "Grand Tower at Arjan",
    "developer": "Emaar Properties",
    "location": "Arjan",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 13,000,000",
    "rawPrice": 13000000,
    "completionDate": "Q1 2028",
    "paymentPlan": "50/20 Payment Plan",
    "bedrooms": "1",
    "bathrooms": "1",
    "area": "Starting from 600 sqft",
    "roi": "9%",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Emaar Properties located in the heart of Arjan. Built in 2028.",
    "downPayment": "13%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1028,
    "title": "Vista Estates at Dubai",
    "developer": "MAG Property Development",
    "location": "Dubai South",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 3,000,000",
    "rawPrice": 3000000,
    "completionDate": "Q4 2028",
    "paymentPlan": "80/60 Payment Plan",
    "bedrooms": "3-5",
    "bathrooms": "3-5",
    "area": "Starting from 1,800 sqft",
    "roi": "12%",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by MAG Property Development located in the heart of Dubai South. Built in 2028.",
    "downPayment": "23%",
    "isFeatured": true,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1029,
    "title": "Exclusive Views at Dubai",
    "developer": "Nshama",
    "location": "Dubai Hills Estate",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 15,500,000",
    "rawPrice": 15500000,
    "completionDate": "Q4 2026",
    "paymentPlan": "50/30 Payment Plan",
    "bedrooms": "1-2",
    "bathrooms": "1-2",
    "area": "Starting from 600 sqft",
    "roi": "5%",
    "image": "https://images.unsplash.com/photo-1449844908441-8829872d2607?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Nshama located in the heart of Dubai Hills Estate. Built in 2026.",
    "downPayment": "24%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1030,
    "title": "Exclusive Tower at Jumeirah",
    "developer": "Sobha Realty",
    "location": "Jumeirah Village Circle (JVC)",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 4,600,000",
    "rawPrice": 4600000,
    "completionDate": "Q1 2023",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1-2",
    "bathrooms": "1-2",
    "area": "Starting from 600 sqft",
    "roi": "11%",
    "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Sobha Realty located in the heart of Jumeirah Village Circle (JVC). Built in 2023.",
    "downPayment": "100%",
    "isFeatured": true,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1031,
    "title": "Exclusive Heights at Meydan",
    "developer": "Emaar Properties",
    "location": "Meydan",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 12,200,000",
    "rawPrice": 12200000,
    "completionDate": "Q3 2019",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "2-4",
    "bathrooms": "2-4",
    "area": "Starting from 1,200 sqft",
    "roi": "11%",
    "image": "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Emaar Properties located in the heart of Meydan. Built in 2019.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1032,
    "title": "Luxury Gardens at Dubai",
    "developer": "Select Group",
    "location": "Dubai South",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 8,800,000",
    "rawPrice": 8800000,
    "completionDate": "Q1 2020",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "3",
    "bathrooms": "3",
    "area": "Starting from 1,800 sqft",
    "roi": "10%",
    "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Select Group located in the heart of Dubai South. Built in 2020.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1033,
    "title": "Vista Park at Town",
    "developer": "Danube Properties",
    "location": "Town Square",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 6,300,000",
    "rawPrice": 6300000,
    "completionDate": "Q1 2030",
    "paymentPlan": "60/50 Payment Plan",
    "bedrooms": "1-3",
    "bathrooms": "1-3",
    "area": "Starting from 600 sqft",
    "roi": "6%",
    "image": "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Danube Properties located in the heart of Town Square. Built in 2030.",
    "downPayment": "18%",
    "isFeatured": true,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1034,
    "title": "Luxury Villas at Dubai",
    "developer": "Nshama",
    "location": "Dubai South",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 11,900,000",
    "rawPrice": 11900000,
    "completionDate": "Q2 2019",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "3",
    "bathrooms": "3",
    "area": "Starting from 1,800 sqft",
    "roi": "12%",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Nshama located in the heart of Dubai South. Built in 2019.",
    "downPayment": "100%",
    "isFeatured": true,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1035,
    "title": "Grand Estates at Meydan",
    "developer": "DAMAC Properties",
    "location": "Meydan",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 3,500,000",
    "rawPrice": 3500000,
    "completionDate": "Q2 2030",
    "paymentPlan": "70/60 Payment Plan",
    "bedrooms": "3-4",
    "bathrooms": "3-4",
    "area": "Starting from 1,800 sqft",
    "roi": "12%",
    "image": "https://images.unsplash.com/photo-1449844908441-8829872d2607?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by DAMAC Properties located in the heart of Meydan. Built in 2030.",
    "downPayment": "21%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1036,
    "title": "Elite Park at Jumeirah",
    "developer": "Deyaar",
    "location": "Jumeirah Lake Towers (JLT)",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 14,700,000",
    "rawPrice": 14700000,
    "completionDate": "Q1 2021",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4-5",
    "bathrooms": "4-5",
    "area": "Starting from 2,400 sqft",
    "roi": "5%",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Deyaar located in the heart of Jumeirah Lake Towers (JLT). Built in 2021.",
    "downPayment": "100%",
    "isFeatured": true,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1037,
    "title": "Elite Villas at Al",
    "developer": "MAG Property Development",
    "location": "Al Furjan",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 11,500,000",
    "rawPrice": 11500000,
    "completionDate": "Q4 2028",
    "paymentPlan": "80/40 Payment Plan",
    "bedrooms": "1-2",
    "bathrooms": "1-2",
    "area": "Starting from 600 sqft",
    "roi": "5%",
    "image": "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by MAG Property Development located in the heart of Al Furjan. Built in 2028.",
    "downPayment": "25%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1038,
    "title": "Vista Boulevard at Palm",
    "developer": "Azizi Developments",
    "location": "Palm Jumeirah",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 2,400,000",
    "rawPrice": 2400000,
    "completionDate": "Q4 2029",
    "paymentPlan": "40/20 Payment Plan",
    "bedrooms": "4-5",
    "bathrooms": "4-5",
    "area": "Starting from 2,400 sqft",
    "roi": "11%",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Azizi Developments located in the heart of Palm Jumeirah. Built in 2029.",
    "downPayment": "16%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1039,
    "title": "Heights Residences at Al",
    "developer": "Select Group",
    "location": "Al Furjan",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 4,200,000",
    "rawPrice": 4200000,
    "completionDate": "Q3 2020",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "3-5",
    "bathrooms": "3-5",
    "area": "Starting from 1,800 sqft",
    "roi": "12%",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Select Group located in the heart of Al Furjan. Built in 2020.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1040,
    "title": "Vista Views at Meydan",
    "developer": "DAMAC Properties",
    "location": "Meydan",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 12,600,000",
    "rawPrice": 12600000,
    "completionDate": "Q4 2025",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "2",
    "bathrooms": "2",
    "area": "Starting from 1,200 sqft",
    "roi": "10%",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by DAMAC Properties located in the heart of Meydan. Built in 2025.",
    "downPayment": "100%",
    "isFeatured": true,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1041,
    "title": "Elite Heights at Al",
    "developer": "Deyaar",
    "location": "Al Furjan",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 9,600,000",
    "rawPrice": 9600000,
    "completionDate": "Q1 2023",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1",
    "bathrooms": "1",
    "area": "Starting from 600 sqft",
    "roi": "7%",
    "image": "https://images.unsplash.com/photo-1449844908441-8829872d2607?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Deyaar located in the heart of Al Furjan. Built in 2023.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1042,
    "title": "Royal Heights at Dubai",
    "developer": "Nakheel",
    "location": "Dubai South",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 6,300,000",
    "rawPrice": 6300000,
    "completionDate": "Q4 2022",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1-2",
    "bathrooms": "1-2",
    "area": "Starting from 600 sqft",
    "roi": "8%",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Nakheel located in the heart of Dubai South. Built in 2022.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1043,
    "title": "Exclusive Park at Al",
    "developer": "Emaar Properties",
    "location": "Al Furjan",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 5,600,000",
    "rawPrice": 5600000,
    "completionDate": "Q2 2022",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4",
    "bathrooms": "4",
    "area": "Starting from 2,400 sqft",
    "roi": "5%",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Emaar Properties located in the heart of Al Furjan. Built in 2022.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1044,
    "title": "Elite Park at Downtown",
    "developer": "Omniyat",
    "location": "Downtown Dubai",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 10,700,000",
    "rawPrice": 10700000,
    "completionDate": "Q1 2025",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1-3",
    "bathrooms": "1-3",
    "area": "Starting from 600 sqft",
    "roi": "11%",
    "image": "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Omniyat located in the heart of Downtown Dubai. Built in 2025.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1045,
    "title": "Vista Park at Jumeirah",
    "developer": "DAMAC Properties",
    "location": "Jumeirah Lake Towers (JLT)",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 15,800,000",
    "rawPrice": 15800000,
    "completionDate": "Q3 2026",
    "paymentPlan": "50/20 Payment Plan",
    "bedrooms": "4-6",
    "bathrooms": "4-6",
    "area": "Starting from 2,400 sqft",
    "roi": "8%",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by DAMAC Properties located in the heart of Jumeirah Lake Towers (JLT). Built in 2026.",
    "downPayment": "14%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1046,
    "title": "Royal Park at Jumeirah",
    "developer": "MAG Property Development",
    "location": "Jumeirah Village Circle (JVC)",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 18,900,000",
    "rawPrice": 18900000,
    "completionDate": "Q3 2022",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1-2",
    "bathrooms": "1-2",
    "area": "Starting from 600 sqft",
    "roi": "10%",
    "image": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by MAG Property Development located in the heart of Jumeirah Village Circle (JVC). Built in 2022.",
    "downPayment": "100%",
    "isFeatured": true,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1047,
    "title": "Royal Views at Jumeirah",
    "developer": "Danube Properties",
    "location": "Jumeirah Lake Towers (JLT)",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 4,100,000",
    "rawPrice": 4100000,
    "completionDate": "Q3 2029",
    "paymentPlan": "60/60 Payment Plan",
    "bedrooms": "2",
    "bathrooms": "2",
    "area": "Starting from 1,200 sqft",
    "roi": "11%",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by Danube Properties located in the heart of Jumeirah Lake Towers (JLT). Built in 2029.",
    "downPayment": "23%",
    "isFeatured": true,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1048,
    "title": "Exclusive Villas at Sobha",
    "developer": "Nakheel",
    "location": "Sobha Hartland",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 5,100,000",
    "rawPrice": 5100000,
    "completionDate": "Q2 2026",
    "paymentPlan": "40/50 Payment Plan",
    "bedrooms": "3-5",
    "bathrooms": "3-5",
    "area": "Starting from 1,800 sqft",
    "roi": "8%",
    "image": "https://images.unsplash.com/photo-1600566753086-00f18efc2294?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Nakheel located in the heart of Sobha Hartland. Built in 2026.",
    "downPayment": "18%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1049,
    "title": "Premium Boulevard at Business",
    "developer": "Deyaar",
    "location": "Business Bay",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 3,900,000",
    "rawPrice": 3900000,
    "completionDate": "Q2 2030",
    "paymentPlan": "50/30 Payment Plan",
    "bedrooms": "4-6",
    "bathrooms": "4-6",
    "area": "Starting from 2,400 sqft",
    "roi": "5%",
    "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by Deyaar located in the heart of Business Bay. Built in 2030.",
    "downPayment": "21%",
    "isFeatured": true,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1050,
    "title": "Vista Views at Jumeirah",
    "developer": "Omniyat",
    "location": "Jumeirah Lake Towers (JLT)",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 15,400,000",
    "rawPrice": 15400000,
    "completionDate": "Q1 2022",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4-6",
    "bathrooms": "4-6",
    "area": "Starting from 2,400 sqft",
    "roi": "10%",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Omniyat located in the heart of Jumeirah Lake Towers (JLT). Built in 2022.",
    "downPayment": "100%",
    "isFeatured": true,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1051,
    "title": "Vista Park at Downtown",
    "developer": "MAG Property Development",
    "location": "Downtown Dubai",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 11,200,000",
    "rawPrice": 11200000,
    "completionDate": "Q3 2027",
    "paymentPlan": "60/60 Payment Plan",
    "bedrooms": "2-3",
    "bathrooms": "2-3",
    "area": "Starting from 1,200 sqft",
    "roi": "5%",
    "image": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by MAG Property Development located in the heart of Downtown Dubai. Built in 2027.",
    "downPayment": "18%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1052,
    "title": "Vista Views at Dubai",
    "developer": "Deyaar",
    "location": "Dubai Hills Estate",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 5,000,000",
    "rawPrice": 5000000,
    "completionDate": "Q2 2020",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1",
    "bathrooms": "1",
    "area": "Starting from 600 sqft",
    "roi": "12%",
    "image": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by Deyaar located in the heart of Dubai Hills Estate. Built in 2020.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1053,
    "title": "Exclusive Residences at Palm",
    "developer": "Danube Properties",
    "location": "Palm Jumeirah",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 1,400,000",
    "rawPrice": 1400000,
    "completionDate": "Q3 2026",
    "paymentPlan": "40/50 Payment Plan",
    "bedrooms": "3-5",
    "bathrooms": "3-5",
    "area": "Starting from 1,800 sqft",
    "roi": "5%",
    "image": "https://images.unsplash.com/photo-1600566753086-00f18efc2294?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by Danube Properties located in the heart of Palm Jumeirah. Built in 2026.",
    "downPayment": "20%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1054,
    "title": "Heights Gardens at Al",
    "developer": "Nakheel",
    "location": "Al Furjan",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 9,200,000",
    "rawPrice": 9200000,
    "completionDate": "Q2 2021",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "2",
    "bathrooms": "2",
    "area": "Starting from 1,200 sqft",
    "roi": "5%",
    "image": "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Nakheel located in the heart of Al Furjan. Built in 2021.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1055,
    "title": "Exclusive Park at Dubai",
    "developer": "Emaar Properties",
    "location": "Dubai Creek Harbour",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 12,400,000",
    "rawPrice": 12400000,
    "completionDate": "Q3 2023",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4-6",
    "bathrooms": "4-6",
    "area": "Starting from 2,400 sqft",
    "roi": "6%",
    "image": "https://images.unsplash.com/photo-1600566753086-00f18efc2294?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Emaar Properties located in the heart of Dubai Creek Harbour. Built in 2023.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1056,
    "title": "Signature Heights at Sobha",
    "developer": "Emaar Properties",
    "location": "Sobha Hartland",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 11,100,000",
    "rawPrice": 11100000,
    "completionDate": "Q2 2026",
    "paymentPlan": "40/40 Payment Plan",
    "bedrooms": "1-3",
    "bathrooms": "1-3",
    "area": "Starting from 600 sqft",
    "roi": "9%",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Emaar Properties located in the heart of Sobha Hartland. Built in 2026.",
    "downPayment": "16%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1057,
    "title": "Vista Views at Jumeirah",
    "developer": "Dubai Properties",
    "location": "Jumeirah Lake Towers (JLT)",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 7,800,000",
    "rawPrice": 7800000,
    "completionDate": "Q1 2030",
    "paymentPlan": "40/20 Payment Plan",
    "bedrooms": "1-2",
    "bathrooms": "1-2",
    "area": "Starting from 600 sqft",
    "roi": "7%",
    "image": "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Dubai Properties located in the heart of Jumeirah Lake Towers (JLT). Built in 2030.",
    "downPayment": "14%",
    "isFeatured": true,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1058,
    "title": "Premium Gardens at Al",
    "developer": "Nshama",
    "location": "Al Furjan",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 7,000,000",
    "rawPrice": 7000000,
    "completionDate": "Q3 2028",
    "paymentPlan": "40/20 Payment Plan",
    "bedrooms": "4-6",
    "bathrooms": "4-6",
    "area": "Starting from 2,400 sqft",
    "roi": "12%",
    "image": "https://images.unsplash.com/photo-1600566753086-00f18efc2294?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Nshama located in the heart of Al Furjan. Built in 2028.",
    "downPayment": "19%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1059,
    "title": "Exclusive Estates at Jumeirah",
    "developer": "Dubai Properties",
    "location": "Jumeirah Village Circle (JVC)",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 4,400,000",
    "rawPrice": 4400000,
    "completionDate": "Q1 2021",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1-3",
    "bathrooms": "1-3",
    "area": "Starting from 600 sqft",
    "roi": "9%",
    "image": "https://images.unsplash.com/photo-1449844908441-8829872d2607?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by Dubai Properties located in the heart of Jumeirah Village Circle (JVC). Built in 2021.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1060,
    "title": "Vista Park at Meydan",
    "developer": "Omniyat",
    "location": "Meydan",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 12,400,000",
    "rawPrice": 12400000,
    "completionDate": "Q2 2023",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4",
    "bathrooms": "4",
    "area": "Starting from 2,400 sqft",
    "roi": "6%",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Omniyat located in the heart of Meydan. Built in 2023.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1061,
    "title": "Royal Villas at Arjan",
    "developer": "Sobha Realty",
    "location": "Arjan",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 14,500,000",
    "rawPrice": 14500000,
    "completionDate": "Q2 2021",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "3-4",
    "bathrooms": "3-4",
    "area": "Starting from 1,800 sqft",
    "roi": "11%",
    "image": "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Sobha Realty located in the heart of Arjan. Built in 2021.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1062,
    "title": "Vista Gardens at Dubai",
    "developer": "Emaar Properties",
    "location": "Dubai South",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 14,600,000",
    "rawPrice": 14600000,
    "completionDate": "Q3 2030",
    "paymentPlan": "60/30 Payment Plan",
    "bedrooms": "4-5",
    "bathrooms": "4-5",
    "area": "Starting from 2,400 sqft",
    "roi": "5%",
    "image": "https://images.unsplash.com/photo-1449844908441-8829872d2607?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Emaar Properties located in the heart of Dubai South. Built in 2030.",
    "downPayment": "21%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1063,
    "title": "Vista Villas at Jumeirah",
    "developer": "Binghatti Developers",
    "location": "Jumeirah Lake Towers (JLT)",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 16,700,000",
    "rawPrice": 16700000,
    "completionDate": "Q4 2025",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1-2",
    "bathrooms": "1-2",
    "area": "Starting from 600 sqft",
    "roi": "7%",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Binghatti Developers located in the heart of Jumeirah Lake Towers (JLT). Built in 2025.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1064,
    "title": "Royal Gardens at Jumeirah",
    "developer": "Nakheel",
    "location": "Jumeirah Village Circle (JVC)",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 10,400,000",
    "rawPrice": 10400000,
    "completionDate": "Q2 2027",
    "paymentPlan": "50/60 Payment Plan",
    "bedrooms": "4-6",
    "bathrooms": "4-6",
    "area": "Starting from 2,400 sqft",
    "roi": "8%",
    "image": "https://images.unsplash.com/photo-1449844908441-8829872d2607?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Nakheel located in the heart of Jumeirah Village Circle (JVC). Built in 2027.",
    "downPayment": "19%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1065,
    "title": "Premium Residences at Business",
    "developer": "Danube Properties",
    "location": "Business Bay",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 4,400,000",
    "rawPrice": 4400000,
    "completionDate": "Q2 2024",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4-5",
    "bathrooms": "4-5",
    "area": "Starting from 2,400 sqft",
    "roi": "7%",
    "image": "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by Danube Properties located in the heart of Business Bay. Built in 2024.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1066,
    "title": "Elite Estates at Arjan",
    "developer": "DAMAC Properties",
    "location": "Arjan",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 12,000,000",
    "rawPrice": 12000000,
    "completionDate": "Q4 2024",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "2-3",
    "bathrooms": "2-3",
    "area": "Starting from 1,200 sqft",
    "roi": "6%",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by DAMAC Properties located in the heart of Arjan. Built in 2024.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1067,
    "title": "Luxury Park at Dubai",
    "developer": "Ellington Properties",
    "location": "Dubai Marina",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 14,700,000",
    "rawPrice": 14700000,
    "completionDate": "Q4 2022",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4",
    "bathrooms": "4",
    "area": "Starting from 2,400 sqft",
    "roi": "7%",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Ellington Properties located in the heart of Dubai Marina. Built in 2022.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1068,
    "title": "Luxury Estates at Al",
    "developer": "Omniyat",
    "location": "Al Furjan",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 10,100,000",
    "rawPrice": 10100000,
    "completionDate": "Q4 2020",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1-3",
    "bathrooms": "1-3",
    "area": "Starting from 600 sqft",
    "roi": "9%",
    "image": "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Omniyat located in the heart of Al Furjan. Built in 2020.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1069,
    "title": "Royal Gardens at Al",
    "developer": "MAG Property Development",
    "location": "Al Furjan",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 3,100,000",
    "rawPrice": 3100000,
    "completionDate": "Q2 2027",
    "paymentPlan": "80/50 Payment Plan",
    "bedrooms": "2-4",
    "bathrooms": "2-4",
    "area": "Starting from 1,200 sqft",
    "roi": "8%",
    "image": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by MAG Property Development located in the heart of Al Furjan. Built in 2027.",
    "downPayment": "21%",
    "isFeatured": true,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1070,
    "title": "Exclusive Heights at Jumeirah",
    "developer": "Danube Properties",
    "location": "Jumeirah Village Circle (JVC)",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 14,500,000",
    "rawPrice": 14500000,
    "completionDate": "Q1 2027",
    "paymentPlan": "80/40 Payment Plan",
    "bedrooms": "1-3",
    "bathrooms": "1-3",
    "area": "Starting from 600 sqft",
    "roi": "11%",
    "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Danube Properties located in the heart of Jumeirah Village Circle (JVC). Built in 2027.",
    "downPayment": "17%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1071,
    "title": "Oasis Tower at Downtown",
    "developer": "Deyaar",
    "location": "Downtown Dubai",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 2,600,000",
    "rawPrice": 2600000,
    "completionDate": "Q4 2024",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4",
    "bathrooms": "4",
    "area": "Starting from 2,400 sqft",
    "roi": "7%",
    "image": "https://images.unsplash.com/photo-1449844908441-8829872d2607?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by Deyaar located in the heart of Downtown Dubai. Built in 2024.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1072,
    "title": "Luxury Estates at Jumeirah",
    "developer": "Azizi Developments",
    "location": "Jumeirah Village Circle (JVC)",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 17,600,000",
    "rawPrice": 17600000,
    "completionDate": "Q1 2025",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1",
    "bathrooms": "1",
    "area": "Starting from 600 sqft",
    "roi": "7%",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Azizi Developments located in the heart of Jumeirah Village Circle (JVC). Built in 2025.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1073,
    "title": "Exclusive Estates at Dubai",
    "developer": "Binghatti Developers",
    "location": "Dubai Sports City",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 6,000,000",
    "rawPrice": 6000000,
    "completionDate": "Q3 2028",
    "paymentPlan": "60/50 Payment Plan",
    "bedrooms": "3",
    "bathrooms": "3",
    "area": "Starting from 1,800 sqft",
    "roi": "10%",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Binghatti Developers located in the heart of Dubai Sports City. Built in 2028.",
    "downPayment": "12%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1074,
    "title": "Elite Gardens at Sobha",
    "developer": "Sobha Realty",
    "location": "Sobha Hartland",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 11,100,000",
    "rawPrice": 11100000,
    "completionDate": "Q1 2024",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4-6",
    "bathrooms": "4-6",
    "area": "Starting from 2,400 sqft",
    "roi": "6%",
    "image": "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Sobha Realty located in the heart of Sobha Hartland. Built in 2024.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1075,
    "title": "Elite Residences at Jumeirah",
    "developer": "Select Group",
    "location": "Jumeirah Lake Towers (JLT)",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 14,500,000",
    "rawPrice": 14500000,
    "completionDate": "Q2 2021",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4-6",
    "bathrooms": "4-6",
    "area": "Starting from 2,400 sqft",
    "roi": "8%",
    "image": "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Select Group located in the heart of Jumeirah Lake Towers (JLT). Built in 2021.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1076,
    "title": "Premium Residences at Dubai",
    "developer": "DAMAC Properties",
    "location": "Dubai South",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 4,100,000",
    "rawPrice": 4100000,
    "completionDate": "Q2 2025",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1",
    "bathrooms": "1",
    "area": "Starting from 600 sqft",
    "roi": "9%",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by DAMAC Properties located in the heart of Dubai South. Built in 2025.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1077,
    "title": "Grand Estates at Town",
    "developer": "DAMAC Properties",
    "location": "Town Square",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 11,400,000",
    "rawPrice": 11400000,
    "completionDate": "Q2 2028",
    "paymentPlan": "40/50 Payment Plan",
    "bedrooms": "4",
    "bathrooms": "4",
    "area": "Starting from 2,400 sqft",
    "roi": "6%",
    "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by DAMAC Properties located in the heart of Town Square. Built in 2028.",
    "downPayment": "12%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1078,
    "title": "Premium Estates at Al",
    "developer": "Sobha Realty",
    "location": "Al Furjan",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 12,700,000",
    "rawPrice": 12700000,
    "completionDate": "Q4 2027",
    "paymentPlan": "50/20 Payment Plan",
    "bedrooms": "1-3",
    "bathrooms": "1-3",
    "area": "Starting from 600 sqft",
    "roi": "10%",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Sobha Realty located in the heart of Al Furjan. Built in 2027.",
    "downPayment": "23%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1079,
    "title": "Elite Villas at Business",
    "developer": "Meraas",
    "location": "Business Bay",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 17,500,000",
    "rawPrice": 17500000,
    "completionDate": "Q2 2030",
    "paymentPlan": "80/40 Payment Plan",
    "bedrooms": "2-4",
    "bathrooms": "2-4",
    "area": "Starting from 1,200 sqft",
    "roi": "9%",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Meraas located in the heart of Business Bay. Built in 2030.",
    "downPayment": "17%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1080,
    "title": "Royal Park at Al",
    "developer": "Deyaar",
    "location": "Al Furjan",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 4,800,000",
    "rawPrice": 4800000,
    "completionDate": "Q3 2025",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1",
    "bathrooms": "1",
    "area": "Starting from 600 sqft",
    "roi": "6%",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by Deyaar located in the heart of Al Furjan. Built in 2025.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1081,
    "title": "Heights Heights at Sobha",
    "developer": "Binghatti Developers",
    "location": "Sobha Hartland",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 13,400,000",
    "rawPrice": 13400000,
    "completionDate": "Q1 2024",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4",
    "bathrooms": "4",
    "area": "Starting from 2,400 sqft",
    "roi": "9%",
    "image": "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Binghatti Developers located in the heart of Sobha Hartland. Built in 2024.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1082,
    "title": "Exclusive Villas at Dubai",
    "developer": "MAG Property Development",
    "location": "Dubai Marina",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 12,000,000",
    "rawPrice": 12000000,
    "completionDate": "Q2 2025",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1",
    "bathrooms": "1",
    "area": "Starting from 600 sqft",
    "roi": "9%",
    "image": "https://images.unsplash.com/photo-1449844908441-8829872d2607?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by MAG Property Development located in the heart of Dubai Marina. Built in 2025.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1083,
    "title": "Elite Gardens at Arjan",
    "developer": "Omniyat",
    "location": "Arjan",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 6,700,000",
    "rawPrice": 6700000,
    "completionDate": "Q1 2030",
    "paymentPlan": "70/50 Payment Plan",
    "bedrooms": "4",
    "bathrooms": "4",
    "area": "Starting from 2,400 sqft",
    "roi": "6%",
    "image": "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Omniyat located in the heart of Arjan. Built in 2030.",
    "downPayment": "25%",
    "isFeatured": true,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1084,
    "title": "Vista Gardens at Arjan",
    "developer": "Azizi Developments",
    "location": "Arjan",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 19,400,000",
    "rawPrice": 19400000,
    "completionDate": "Q1 2022",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4-5",
    "bathrooms": "4-5",
    "area": "Starting from 2,400 sqft",
    "roi": "7%",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Azizi Developments located in the heart of Arjan. Built in 2022.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1085,
    "title": "Exclusive Park at Dubai",
    "developer": "MAG Property Development",
    "location": "Dubai Hills Estate",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 6,100,000",
    "rawPrice": 6100000,
    "completionDate": "Q1 2026",
    "paymentPlan": "70/30 Payment Plan",
    "bedrooms": "4",
    "bathrooms": "4",
    "area": "Starting from 2,400 sqft",
    "roi": "11%",
    "image": "https://images.unsplash.com/photo-1449844908441-8829872d2607?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by MAG Property Development located in the heart of Dubai Hills Estate. Built in 2026.",
    "downPayment": "25%",
    "isFeatured": true,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1086,
    "title": "Vista Villas at Dubai",
    "developer": "Deyaar",
    "location": "Dubai Hills Estate",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 4,900,000",
    "rawPrice": 4900000,
    "completionDate": "Q2 2026",
    "paymentPlan": "40/40 Payment Plan",
    "bedrooms": "4-5",
    "bathrooms": "4-5",
    "area": "Starting from 2,400 sqft",
    "roi": "6%",
    "image": "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Deyaar located in the heart of Dubai Hills Estate. Built in 2026.",
    "downPayment": "12%",
    "isFeatured": true,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1087,
    "title": "Oasis Gardens at Downtown",
    "developer": "Binghatti Developers",
    "location": "Downtown Dubai",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 2,700,000",
    "rawPrice": 2700000,
    "completionDate": "Q2 2027",
    "paymentPlan": "60/50 Payment Plan",
    "bedrooms": "4-6",
    "bathrooms": "4-6",
    "area": "Starting from 2,400 sqft",
    "roi": "6%",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by Binghatti Developers located in the heart of Downtown Dubai. Built in 2027.",
    "downPayment": "19%",
    "isFeatured": true,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1088,
    "title": "Oasis Park at Dubai",
    "developer": "MAG Property Development",
    "location": "Dubai Sports City",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 3,200,000",
    "rawPrice": 3200000,
    "completionDate": "Q1 2027",
    "paymentPlan": "40/60 Payment Plan",
    "bedrooms": "4-5",
    "bathrooms": "4-5",
    "area": "Starting from 2,400 sqft",
    "roi": "8%",
    "image": "https://images.unsplash.com/photo-1600566753086-00f18efc2294?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by MAG Property Development located in the heart of Dubai Sports City. Built in 2027.",
    "downPayment": "23%",
    "isFeatured": true,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1089,
    "title": "Oasis Park at Al",
    "developer": "Sobha Realty",
    "location": "Al Furjan",
    "city": "Dubai",
    "type": "Penthouse",
    "startingPrice": "AED 10,500,000",
    "rawPrice": 10500000,
    "completionDate": "Q2 2019",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4",
    "bathrooms": "4",
    "area": "Starting from 2,400 sqft",
    "roi": "7%",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning penthouse developed by Sobha Realty located in the heart of Al Furjan. Built in 2019.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1090,
    "title": "Heights Estates at Dubai",
    "developer": "Nakheel",
    "location": "Dubai Creek Harbour",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 14,100,000",
    "rawPrice": 14100000,
    "completionDate": "Q1 2023",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "2-3",
    "bathrooms": "2-3",
    "area": "Starting from 1,200 sqft",
    "roi": "8%",
    "image": "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Nakheel located in the heart of Dubai Creek Harbour. Built in 2023.",
    "downPayment": "100%",
    "isFeatured": true,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1091,
    "title": "Exclusive Heights at Arjan",
    "developer": "Nakheel",
    "location": "Arjan",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 12,300,000",
    "rawPrice": 12300000,
    "completionDate": "Q2 2025",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "2-4",
    "bathrooms": "2-4",
    "area": "Starting from 1,200 sqft",
    "roi": "6%",
    "image": "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Nakheel located in the heart of Arjan. Built in 2025.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1092,
    "title": "Premium Residences at Dubai",
    "developer": "Deyaar",
    "location": "Dubai Creek Harbour",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 8,800,000",
    "rawPrice": 8800000,
    "completionDate": "Q1 2027",
    "paymentPlan": "40/20 Payment Plan",
    "bedrooms": "2-3",
    "bathrooms": "2-3",
    "area": "Starting from 1,200 sqft",
    "roi": "6%",
    "image": "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Deyaar located in the heart of Dubai Creek Harbour. Built in 2027.",
    "downPayment": "22%",
    "isFeatured": true,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1093,
    "title": "Luxury Boulevard at Dubai",
    "developer": "Meraas",
    "location": "Dubai Marina",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 17,400,000",
    "rawPrice": 17400000,
    "completionDate": "Q3 2027",
    "paymentPlan": "40/40 Payment Plan",
    "bedrooms": "1-2",
    "bathrooms": "1-2",
    "area": "Starting from 600 sqft",
    "roi": "7%",
    "image": "https://images.unsplash.com/photo-1600566753086-00f18efc2294?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Meraas located in the heart of Dubai Marina. Built in 2027.",
    "downPayment": "24%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1094,
    "title": "Heights Residences at Al",
    "developer": "Omniyat",
    "location": "Al Furjan",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 8,000,000",
    "rawPrice": 8000000,
    "completionDate": "Q1 2021",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4-5",
    "bathrooms": "4-5",
    "area": "Starting from 2,400 sqft",
    "roi": "5%",
    "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Omniyat located in the heart of Al Furjan. Built in 2021.",
    "downPayment": "100%",
    "isFeatured": true,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1095,
    "title": "Grand Boulevard at Meydan",
    "developer": "Deyaar",
    "location": "Meydan",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 1,800,000",
    "rawPrice": 1800000,
    "completionDate": "Q1 2027",
    "paymentPlan": "80/40 Payment Plan",
    "bedrooms": "4-5",
    "bathrooms": "4-5",
    "area": "Starting from 2,400 sqft",
    "roi": "10%",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by Deyaar located in the heart of Meydan. Built in 2027.",
    "downPayment": "21%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1096,
    "title": "Grand Estates at Jumeirah",
    "developer": "DAMAC Properties",
    "location": "Jumeirah Lake Towers (JLT)",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 2,500,000",
    "rawPrice": 2500000,
    "completionDate": "Q4 2028",
    "paymentPlan": "70/50 Payment Plan",
    "bedrooms": "3-5",
    "bathrooms": "3-5",
    "area": "Starting from 1,800 sqft",
    "roi": "11%",
    "image": "https://images.unsplash.com/photo-1600566753086-00f18efc2294?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by DAMAC Properties located in the heart of Jumeirah Lake Towers (JLT). Built in 2028.",
    "downPayment": "17%",
    "isFeatured": true,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1097,
    "title": "Heights Villas at Meydan",
    "developer": "MAG Property Development",
    "location": "Meydan",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 8,900,000",
    "rawPrice": 8900000,
    "completionDate": "Q2 2025",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4-5",
    "bathrooms": "4-5",
    "area": "Starting from 2,400 sqft",
    "roi": "12%",
    "image": "https://images.unsplash.com/photo-1449844908441-8829872d2607?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by MAG Property Development located in the heart of Meydan. Built in 2025.",
    "downPayment": "100%",
    "isFeatured": false,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1098,
    "title": "Premium Residences at Arjan",
    "developer": "Meraas",
    "location": "Arjan",
    "city": "Dubai",
    "type": "Townhouse",
    "startingPrice": "AED 13,700,000",
    "rawPrice": 13700000,
    "completionDate": "Q4 2030",
    "paymentPlan": "80/40 Payment Plan",
    "bedrooms": "1-3",
    "bathrooms": "1-3",
    "area": "Starting from 600 sqft",
    "roi": "6%",
    "image": "https://images.unsplash.com/photo-1449844908441-8829872d2607?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning townhouse developed by Meraas located in the heart of Arjan. Built in 2030.",
    "downPayment": "16%",
    "isFeatured": false,
    "status": "Off-Plan",
    "saleStatus": "On sale"
  },
  {
    "id": 1099,
    "title": "Heights Park at Dubai",
    "developer": "Dubai Properties",
    "location": "Dubai Hills Estate",
    "city": "Dubai",
    "type": "Villa",
    "startingPrice": "AED 17,900,000",
    "rawPrice": 17900000,
    "completionDate": "Q4 2025",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "4",
    "bathrooms": "4",
    "area": "Starting from 2,400 sqft",
    "roi": "5%",
    "image": "https://images.unsplash.com/photo-1600566753086-00f18efc2294?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning villa developed by Dubai Properties located in the heart of Dubai Hills Estate. Built in 2025.",
    "downPayment": "100%",
    "isFeatured": true,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  },
  {
    "id": 1100,
    "title": "Grand Views at Dubai",
    "developer": "Meraas",
    "location": "Dubai South",
    "city": "Dubai",
    "type": "Apartment",
    "startingPrice": "AED 2,100,000",
    "rawPrice": 2100000,
    "completionDate": "Q1 2021",
    "paymentPlan": "100% Cash/Mortgage",
    "bedrooms": "1",
    "bathrooms": "1",
    "area": "Starting from 600 sqft",
    "roi": "11%",
    "image": "https://images.unsplash.com/photo-1600566753086-00f18efc2294?crop=entropy&cs=srgb&fm=jpg&w=1200&q=85",
    "features": [
      "Smart Home",
      "Premium Finishes",
      "Balcony"
    ],
    "amenities": [
      "Swimming Pool",
      "Gymnasium",
      "24/7 Security",
      "Parking"
    ],
    "description": "A stunning apartment developed by Meraas located in the heart of Dubai South. Built in 2021.",
    "downPayment": "100%",
    "isFeatured": true,
    "status": "Completed",
    "saleStatus": "Secondary Market"
  }
];

export function getDummyPropertyDetail(id, props) {
  const p = props.find(x => String(x.id) === String(id)) || props[0];

  return {
    id: p.id,
    name: p.title,
    developer: p.developer,
    city: p.city,
    country: "UAE",
    status: "active",
    is_partner_project: p.isFeatured,
    cover_image_url: p.image,
    post_handover: true,
    sale_status: p.saleStatus || "On sale",
    completion_datetime: p.completionDate.split(' ')[1] + "-12-01T00:00:00Z", // Approximate date parsing
    has_escrow: true,
    coordinates: "25.0805,55.1403",
    overview: p.description,
    website: "https://triadrealty.ae",
    deposit_description: p.downPayment + " On Booking",
    unit_blocks: [
      {
        id: p.id * 10,
        name: `${p.bedrooms.split('-')[0]} Bedroom ${p.type}`,
        unit_type: p.type,
        normalized_type: p.type.toLowerCase(),
        unit_bedrooms: `${p.bedrooms.split('-')[0]} bedroom`,
        units_amount: 50,
        units_area_from: parseInt(p.area.replace(/\D/g,'')) || 1000,
        units_area_to: (parseInt(p.area.replace(/\D/g,'')) || 1000) + 500,
        units_price_from: p.rawPrice,
        units_price_to: p.rawPrice * 1.3,
        area_unit: "sqft",
        price_currency: "AED",
        typical_unit_image_url: p.image
      }
    ],
    payment_plans: [
      { milestone: "Down Payment", percent: parseInt(p.downPayment.replace('%','')) || 20 },
      { milestone: "During Construction", percent: parseInt(p.paymentPlan.split('/')[0]) ? parseInt(p.paymentPlan.split('/')[0]) - parseInt(p.downPayment.replace('%','')) : 40 },
      { milestone: "On Handover", percent: parseInt(p.paymentPlan.split('/')[1]) || 40 }
    ],
    master_plan: [],
    lobby: [],
    interior: [],
    architecture: [],
    buildings: []
  };
}
